language: python
python:
  - "2.7"

dist: trusty
sudo: required

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt


services:
  - docker

before_script:

script:
  - sh -e ci/pycodestyle_tests.sh
  - sh -e ci/pylint_tests.sh

after_success:

after_script:

