# This will be by CI tool to build BMI image that will be used for testing.

# Basing on image stored in docker hub for faster build
FROM bmis/bmi-ci

# Copy source code
USER bmi
COPY ims/ /home/bmi/ims/
COPY tests/ /home/bmi/tests/
COPY scripts/ /home/bmi/scripts/
COPY setup.py /home/bmi/setup.py

# Install
USER root
WORKDIR /home/bmi
RUN python setup.py develop

# Create DB
USER bmi
RUN bmi db ls

# Start dependencies when container starts
CMD dumb-init /home/bmi/runbmi.sh
