FROM centos
RUN yum install -y epel-release 
RUN yum -y update && yum install -y bridge-utils  gcc  httpd  ipmitool libvirt libxml2-devel  libxslt-devel  mod_wsgi net-tools python-pip python-psycopg2 python-virtinst qemu-kvm telnet vconfig virt-install
RUN yum install -y git
RUN yum install -y python-devel
RUN pip install dumb-init

RUN useradd -ms /bin/bash hil
RUN passwd -d hil
RUN passwd -d root
RUN usermod -aG wheel hil

WORKDIR /home/hil
RUN git clone https://github.com/CCI-MOC/hil.git
WORKDIR /home/hil/hil
RUN git reset --hard 477e12097ce7f379056184d43d8f72dfcbe30b5f
RUN python setup.py install
COPY docker/haas.cfg /etc/haas.cfg
COPY docker/haas.cfg ./haas.cfg

USER hil
RUN haas-admin db create

USER root
COPY docker/setupdb.sh ./setupdb.sh
RUN chmod a+x setupdb.sh

USER hil
ENV HAAS_ENDPOINT=http://127.0.0.1:7000
RUN ./setupdb.sh

USER root
RUN chmod 666 /home/hil/haas.db
RUN chown hil:hil /home/hil/haas.db

COPY docker/runhil.sh ./runhil.sh
RUN chmod a+x runhil.sh

RUN cp ./haas.wsgi ./wsgi.py

RUN pip install gunicorn

EXPOSE 7000
USER hil
CMD dumb-init /home/hil/hil/runhil.sh
