#!/usr/bin/python

import threading

import ims.common.config as config

config.load()

from ims.rpc.server.name_server import *
from ims.rpc.server.rpc_server import *

logger = create_logger(__name__)

t1 = threading.Thread(target=start_name_server)
t2 = threading.Thread(target=start_rpc_server)

t1.daemon = True
t2.daemon = True

t1.start()
t2.start()

