#!/usr/bin/python

import multiprocessing

import ims.common.config as config

config.load()

from ims.rpc.server.name_server import start_name_server
from ims.rpc.server.rpc_server import start_rpc_server
from ims.common.log import create_logger

logger = create_logger(__name__)

p1 = multiprocessing.Process(target=start_name_server)
p2 = multiprocessing.Process(target=start_rpc_server)

p1.start()
p2.start()

logger.info("Nameserver Process ID = %s", p1.pid)
logger.info("RPC Server Process ID = %s", p2.pid)

p1.join()
p2.join()
